## Explore Data

Here we provide examples of the Parquet files generated as part of the data pipeline.

In [27]:
import json
import pandas as pd
import polars as pl

from settings import config

DATA_DIR = config("DATA_DIR")

### task_pull_fred

In [19]:
parquet_files = [
    "fred.parquet",
]

for pf in parquet_files:
    print(pf)
    df = pl.scan_parquet(DATA_DIR / pf)
    display(df.collect_schema())
    print(df.collect().shape)
    display(df.head().collect())

fred.parquet

Schema([('GDP', Float64),
        ('CPIAUCNS', Float64),
        ('GDPC1', Float64),
        ('INDPRO', Float64),
        ('PAYEMS', Float64),
        ('DPCREDIT', Float64),
        ('EFFR', Float64),
        ('OBFR', Float64),
        ('SOFR', Float64),
        ('DFEDTARU', Float64),
        ('DFEDTARL', Float64),
        ('WALCL', Float64),
        ('TOTRESNS', Float64),
        ('TREAST', Float64),
        ('CURRCIR', Float64),
        ('GFDEBTN', Float64),
        ('WTREGEN', Float64),
        ('RRPONTSYAWARD', Float64),
        ('RRPONTSYD', Float64),
        ('RPONTSYD', Float64),
        ('WSDONTL', Float64),
        ('Gen_IORB', Float64),
        ('ONRRP_CTPY_LIMIT', Float64),
        ('ONRP_AGG_LIMIT', Float64),
        ('DATE', Datetime(time_unit='ns', time_zone=None))])

(8741, 25)

shape: (5, 25)
┌───────────┬──────────┬───────────┬────────┬───┬──────────┬─────────────┬────────────┬────────────┐
│ GDP       ┆ CPIAUCNS ┆ GDPC1     ┆ INDPRO ┆ … ┆ Gen_IORB ┆ ONRRP_CTPY_ ┆ ONRP_AGG_L ┆ DATE       │
│ ---       ┆ ---      ┆ ---       ┆ ---    ┆   ┆ ---      ┆ LIMIT       ┆ IMIT       ┆ ---        │
│ f64       ┆ f64      ┆ f64       ┆ f64    ┆   ┆ f64      ┆ ---         ┆ ---        ┆ datetime[n │
│           ┆          ┆           ┆        ┆   ┆          ┆ f64         ┆ f64        ┆ s]         │
╞═══════════╪══════════╪═══════════╪════════╪═══╪══════════╪═════════════╪════════════╪════════════╡
│ 10002.179 ┆ 168.8    ┆ 13878.147 ┆ 91.538 ┆ … ┆ null     ┆ null        ┆ null       ┆ 2000-01-01 │
│           ┆          ┆           ┆        ┆   ┆          ┆             ┆            ┆ 00:00:00   │
│ null      ┆ null     ┆ null      ┆ null   ┆ … ┆ null     ┆ null        ┆ null       ┆ 2000-01-03 │
│           ┆          ┆           ┆        ┆   ┆          ┆             ┆            ┆ 00:00:00   │
│ null      ┆ null     ┆ null      ┆ null   ┆ … ┆ null     ┆ null        ┆ null       ┆ 2000-01-04 │
│           ┆          ┆           ┆        ┆   ┆          ┆             ┆            ┆ 00:00:00   │
│ null      ┆ null     ┆ null      ┆ null   ┆ … ┆ null     ┆ null        ┆ null       ┆ 2000-01-05 │
│           ┆          ┆           ┆        ┆   ┆          ┆             ┆            ┆ 00:00:00   │
│ null      ┆ null     ┆ null      ┆ null   ┆ … ┆ null     ┆ null        ┆ null       ┆ 2000-01-06 │
│           ┆          ┆           ┆        ┆   ┆          ┆             ┆            ┆ 00:00:00   │
└───────────┴──────────┴───────────┴────────┴───┴──────────┴─────────────┴────────────┴────────────┘

### task_pull_crsp

In [20]:
parquet_files = [
    "CRSP_DSI.parquet",
    "CRSP_daily_stock.parquet",
    # "market_data.parquet",
]

for pf in parquet_files:
    print(pf)
    df = pl.scan_parquet(DATA_DIR / pf)
    display(df.collect_schema())
    print(df.collect().shape)
    display(df.head().collect())

CRSP_DSI.parquet

Schema([('date', Datetime(time_unit='ns', time_zone=None)),
        ('vwretd', Float64),
        ('vwretx', Float64),
        ('ewretd', Float64),
        ('ewretx', Float64),
        ('totval', Float64),
        ('totcnt', Int64),
        ('usdval', Float64),
        ('usdcnt', Int64),
        ('sprtrn', Float64),
        ('spindx', Float64)])

(6289, 11)

shape: (5, 11)
┌───────────────┬───────────┬───────────┬───────────┬───┬───────────┬────────┬───────────┬─────────┐
│ date          ┆ vwretd    ┆ vwretx    ┆ ewretd    ┆ … ┆ usdval    ┆ usdcnt ┆ sprtrn    ┆ spindx  │
│ ---           ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---    ┆ ---       ┆ ---     │
│ datetime[ns]  ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ i64    ┆ f64       ┆ f64     │
╞═══════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪═════════╡
│ 2000-01-03    ┆ -0.006803 ┆ -0.00681  ┆ 0.002878  ┆ … ┆ 1.7014e10 ┆ 8357   ┆ -0.009549 ┆ 1455.22 │
│ 00:00:00      ┆           ┆           ┆           ┆   ┆           ┆        ┆           ┆         │
│ 2000-01-04    ┆ -0.039652 ┆ -0.039679 ┆ -0.017465 ┆ … ┆ 1.6898e10 ┆ 8357   ┆ -0.038345 ┆ 1399.42 │
│ 00:00:00      ┆           ┆           ┆           ┆   ┆           ┆        ┆           ┆         │
│ 2000-01-05    ┆ -0.000935 ┆ -0.001009 ┆ 0.007821  ┆ … ┆ 1.6229e10 ┆ 8356   ┆ 0.001922  ┆ 1402.11 │
│ 00:00:00      ┆           ┆           ┆           ┆   ┆           ┆        ┆           ┆         │
│ 2000-01-06    ┆ -0.007391 ┆ -0.007547 ┆ 0.004504  ┆ … ┆ 1.6199e10 ┆ 8358   ┆ 0.000956  ┆ 1403.45 │
│ 00:00:00      ┆           ┆           ┆           ┆   ┆           ┆        ┆           ┆         │
│ 2000-01-07    ┆ 0.032516  ┆ 0.032514  ┆ 0.017008  ┆ … ┆ 1.6088e10 ┆ 8353   ┆ 0.02709   ┆ 1441.47 │
│ 00:00:00      ┆           ┆           ┆           ┆   ┆           ┆        ┆           ┆         │
└───────────────┴───────────┴───────────┴───────────┴───┴───────────┴────────┴───────────┴─────────┘

CRSP_daily_stock.parquet

Schema([('permno', Int64),
        ('date', Datetime(time_unit='ns', time_zone=None)),
        ('ret', Float64),
        ('retx', Float64),
        ('prc', Float64),
        ('shrout', Float64),
        ('vol', Float64),
        ('market_cap', Float64)])

(27762983, 8)

shape: (5, 8)
┌────────┬─────────────────────┬───────────┬───────────┬────────┬────────┬────────┬─────────────┐
│ permno ┆ date                ┆ ret       ┆ retx      ┆ prc    ┆ shrout ┆ vol    ┆ market_cap  │
│ ---    ┆ ---                 ┆ ---       ┆ ---       ┆ ---    ┆ ---    ┆ ---    ┆ ---         │
│ i64    ┆ datetime[ns]        ┆ f64       ┆ f64       ┆ f64    ┆ f64    ┆ f64    ┆ f64         │
╞════════╪═════════════════════╪═══════════╪═══════════╪════════╪════════╪════════╪═════════════╡
│ 10001  ┆ 1999-12-27 00:00:00 ┆ 0.011152  ┆ 0.011152  ┆ 8.5    ┆ 2.45e6 ┆ 4515.0 ┆ 2.0825e7    │
│ 10001  ┆ 1999-12-28 00:00:00 ┆ 0.007353  ┆ 0.007353  ┆ 8.5625 ┆ 2.45e6 ┆ 150.0  ┆ 2.0978125e7 │
│ 10001  ┆ 1999-12-29 00:00:00 ┆ -0.007299 ┆ -0.007299 ┆ 8.5    ┆ 2.45e6 ┆ 2444.0 ┆ 2.0825e7    │
│ 10001  ┆ 1999-12-30 00:00:00 ┆ -0.007353 ┆ -0.007353 ┆ 8.4375 ┆ 2.45e6 ┆ 3075.0 ┆ 2.0671875e7 │
│ 10001  ┆ 1999-12-31 00:00:00 ┆ 0.007407  ┆ 0.007407  ┆ -8.5   ┆ 2.45e6 ┆ 0.0    ┆ 2.0825e7    │
└────────┴─────────────────────┴───────────┴───────────┴────────┴────────┴────────┴─────────────┘

### task_pull_sp500_constituents

In [21]:
parquet_files = [
    "sp500_constituents.parquet",
    "sp500_names_lookup.parquet",
]

for pf in parquet_files:
    print(pf)
    df = pl.scan_parquet(DATA_DIR / pf)
    display(df.collect_schema())
    print(df.collect().shape)
    display(df.head().collect())

sp500_constituents.parquet

Schema([('permno', Int64),
        ('indno', Int64),
        ('mbrstartdt', Datetime(time_unit='ns', time_zone=None)),
        ('mbrenddt', Datetime(time_unit='ns', time_zone=None)),
        ('mbrflg', String),
        ('indfam', Int64),
        ('comnam', String),
        ('ticker', String),
        ('ncusip', String),
        ('namedt', Datetime(time_unit='ns', time_zone=None)),
        ('nameenddt', Datetime(time_unit='ns', time_zone=None)),
        ('siccd', Int64),
        ('exchcd', Int64),
        ('gvkey', String),
        ('gsector', String),
        ('ggroup', String),
        ('gind', String),
        ('gsubind', String),
        ('gics_startdt', Datetime(time_unit='ns', time_zone=None)),
        ('gics_enddt', Datetime(time_unit='ns', time_zone=None)),
        ('effstartdt', Datetime(time_unit='ns', time_zone=None)),
        ('effenddt', Datetime(time_unit='ns', time_zone=None))])

(8531, 22)

shape: (5, 22)
┌────────┬─────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ permno ┆ indno   ┆ mbrstartdt ┆ mbrenddt   ┆ … ┆ gics_start ┆ gics_enddt ┆ effstartd ┆ effenddt  │
│ ---    ┆ ---     ┆ ---        ┆ ---        ┆   ┆ dt         ┆ ---        ┆ t         ┆ ---       │
│ i64    ┆ i64     ┆ datetime[n ┆ datetime[n ┆   ┆ ---        ┆ datetime[n ┆ ---       ┆ datetime[ │
│        ┆         ┆ s]         ┆ s]         ┆   ┆ datetime[n ┆ s]         ┆ datetime[ ┆ ns]       │
│        ┆         ┆            ┆            ┆   ┆ s]         ┆            ┆ ns]       ┆           │
╞════════╪═════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 10006  ┆ 1000500 ┆ 1957-03-01 ┆ 1984-07-18 ┆ … ┆ null       ┆ null       ┆ 1957-03-0 ┆ 1984-07-1 │
│        ┆         ┆ 00:00:00   ┆ 00:00:00   ┆   ┆            ┆            ┆ 1         ┆ 8         │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆ 00:00:00  ┆ 00:00:00  │
│ 10006  ┆ 1000500 ┆ 1957-03-01 ┆ 1984-07-18 ┆ … ┆ null       ┆ null       ┆ 1957-03-0 ┆ 1984-07-1 │
│        ┆         ┆ 00:00:00   ┆ 00:00:00   ┆   ┆            ┆            ┆ 1         ┆ 8         │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆ 00:00:00  ┆ 00:00:00  │
│ 10006  ┆ 1000500 ┆ 1957-03-01 ┆ 1984-07-18 ┆ … ┆ null       ┆ null       ┆ 1957-03-0 ┆ 1984-07-1 │
│        ┆         ┆ 00:00:00   ┆ 00:00:00   ┆   ┆            ┆            ┆ 1         ┆ 8         │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆ 00:00:00  ┆ 00:00:00  │
│ 10006  ┆ 1000500 ┆ 1957-03-01 ┆ 1984-07-18 ┆ … ┆ null       ┆ null       ┆ 1957-03-0 ┆ 1984-07-1 │
│        ┆         ┆ 00:00:00   ┆ 00:00:00   ┆   ┆            ┆            ┆ 1         ┆ 8         │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆ 00:00:00  ┆ 00:00:00  │
│ 10006  ┆ 1000500 ┆ 1957-03-01 ┆ 1984-07-18 ┆ … ┆ null       ┆ null       ┆ 1957-03-0 ┆ 1984-07-1 │
│        ┆         ┆ 00:00:00   ┆ 00:00:00   ┆   ┆            ┆            ┆ 1         ┆ 8         │
│        ┆         ┆            ┆            ┆   ┆            ┆            ┆ 00:00:00  ┆ 00:00:00  │
└────────┴─────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

sp500_names_lookup.parquet

Schema([('permno', Int64),
        ('comnam', String),
        ('ticker', String),
        ('comnam_norm', String)])

(3250, 4)

shape: (5, 4)
┌────────┬───────────────────────────┬────────┬─────────────────────┐
│ permno ┆ comnam                    ┆ ticker ┆ comnam_norm         │
│ ---    ┆ ---                       ┆ ---    ┆ ---                 │
│ i64    ┆ str                       ┆ str    ┆ str                 │
╞════════╪═══════════════════════════╪════════╪═════════════════════╡
│ 10006  ┆ A C F INDUSTRIES INC      ┆ null   ┆ a c f               │
│ 10006  ┆ A C F INDUSTRIES INC      ┆ ACF    ┆ a c f               │
│ 10030  ┆ AMERICAN BRAKE SHOE CO    ┆ null   ┆ american brake shoe │
│ 10030  ┆ AMERICAN BRAKE SHOE CO    ┆ ABK    ┆ american brake shoe │
│ 10049  ┆ ABITIBI POWER & PAPER LTD ┆ null   ┆ abitibi power paper │
└────────┴───────────────────────────┴────────┴─────────────────────┘

### task_pull_ravenpack

In [22]:
parquet_files = [
    "ravenpack_djpr.parquet",
]

for pf in parquet_files:
    print(pf)
    df = pl.scan_parquet(DATA_DIR / pf)
    display(df.collect_schema())
    print(df.collect().shape)
    display(df.head().collect())

ravenpack_djpr.parquet

Schema([('timestamp_utc', Datetime(time_unit='ns', time_zone=None)),
        ('rp_story_id', String),
        ('rp_entity_id', String),
        ('entity_type', String),
        ('entity_name', String),
        ('country_code', String),
        ('relevance', Float64),
        ('event_sentiment_score', Float64),
        ('event_relevance', Float64),
        ('event_similarity_key', String),
        ('event_similarity_days', Float64),
        ('topic', String),
        ('rp_group', String),
        ('rp_type', String),
        ('sub_type', String),
        ('property', String),
        ('fact_level', String),
        ('category', String),
        ('news_type', String),
        ('rp_source_id', String),
        ('source_name', String),
        ('provider_id', String),
        ('provider_story_id', String),
        ('headline', String),
        ('css', Float64)])

(28808984, 25)

shape: (5, 25)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────┐
│ timestamp_ ┆ rp_story_i ┆ rp_entity_ ┆ entity_ty ┆ … ┆ provider_ ┆ provider_ ┆ headline  ┆ css   │
│ utc        ┆ d          ┆ id         ┆ pe        ┆   ┆ id        ┆ story_id  ┆ ---       ┆ ---   │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ f64   │
│ datetime[n ┆ str        ┆ str        ┆ str       ┆   ┆ str       ┆ str       ┆           ┆       │
│ s]         ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════╡
│ 2000-01-01 ┆ 52D513EA90 ┆ 047E26     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ Sprint    ┆ -0.06 │
│ 17:52:28   ┆ 40443376A6 ┆            ┆           ┆   ┆           ┆ 1000112   ┆ Says No   ┆       │
│            ┆ B1747B0FA8 ┆            ┆           ┆   ┆           ┆           ┆ Y2K       ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ Rollover  ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ Pr…       ┆       │
│ 2000-01-03 ┆ FF4E46BE5A ┆ 450647     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ Fannie    ┆ 0.0   │
│ 18:43:00   ┆ DD033CC27A ┆            ┆           ┆   ┆           ┆ 3001501   ┆ Mae (FNM) ┆       │
│            ┆ FE43222CCE ┆            ┆           ┆   ┆           ┆           ┆ Block:    ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ 250,00…   ┆       │
│ 2000-01-03 ┆ 82F20FF8EF ┆ 469FA0     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ Optical   ┆ 0.0   │
│ 16:10:41   ┆ AC5644FE10 ┆            ┆           ┆   ┆           ┆ 3000839   ┆ Cable 4Q  ┆       │
│            ┆ C32D134C62 ┆            ┆           ┆   ┆           ┆           ┆ Net 8c A  ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ Dilu…     ┆       │
│ 2000-01-03 ┆ 0FFB77B282 ┆ 469FA0     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ Optical   ┆ 0.0   │
│ 16:15:26   ┆ 7DA2AB088D ┆            ┆           ┆   ┆           ┆ 3000883   ┆ Cable     ┆       │
│            ┆ C48656BF5B ┆            ┆           ┆   ┆           ┆           ┆ Earnings  ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ -2: 4Q,…  ┆       │
│ 2000-01-03 ┆ C1D6E91B80 ┆ 46B511     ┆ COMP      ┆ … ┆ DJ        ┆ DN2000010 ┆ GTE       ┆ 0.0   │
│ 19:43:50   ┆ 613EE8A0AC ┆            ┆           ┆   ┆           ┆ 3001720   ┆ Airphone  ┆       │
│            ┆ D350FFCE84 ┆            ┆           ┆   ┆           ┆           ┆ Unit      ┆       │
│            ┆ …          ┆            ┆           ┆   ┆           ┆           ┆ Unveils   ┆       │
│            ┆            ┆            ┆           ┆   ┆           ┆           ┆ Comm…     ┆       │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────┘

### task_pull_sector_etfs

In [23]:
parquet_files = [
    "sector_etfs.parquet",
]

for pf in parquet_files:
    print(pf)
    df = pl.scan_parquet(DATA_DIR / pf)
    display(df.collect_schema())
    print(df.collect().shape)
    display(df.head().collect())

sector_etfs.parquet

FileNotFoundError: No such file or directory (os error 2): ...d Agentic AI for Finance/Final Project/finm33200_final_project/_data/sector_etfs.parquet (set POLARS_VERBOSE=1 to see full path)

### task_link

In [24]:
parquet_files = [
    "raven_crsp_crosswalk.parquet",
    "ravenpack_djpr_with_permno.parquet",
]

for pf in parquet_files:
    print(pf)
    df = pl.scan_parquet(DATA_DIR / pf)
    display(df.collect_schema())
    print(df.collect().shape)
    display(df.head().collect())

raven_crsp_crosswalk.parquet

Schema([('permno', Int64), ('rp_entity_id', String)])

(16433, 2)

shape: (5, 2)
┌────────┬──────────────┐
│ permno ┆ rp_entity_id │
│ ---    ┆ ---          │
│ i64    ┆ str          │
╞════════╪══════════════╡
│ 57293  ┆ 5F8A7F       │
│ 14704  ┆ 8FEF3B       │
│ 21971  ┆ 23E688       │
│ 12030  ┆ 812BD2       │
│ 80804  ┆ ECC614       │
└────────┴──────────────┘

ravenpack_djpr_with_permno.parquet

Schema([('timestamp_utc', Datetime(time_unit='ns', time_zone=None)),
        ('rp_story_id', String),
        ('rp_entity_id', String),
        ('entity_type', String),
        ('entity_name', String),
        ('country_code', String),
        ('relevance', Float64),
        ('event_sentiment_score', Float64),
        ('event_relevance', Float64),
        ('event_similarity_key', String),
        ('event_similarity_days', Float64),
        ('topic', String),
        ('rp_group', String),
        ('rp_type', String),
        ('sub_type', String),
        ('property', String),
        ('fact_level', String),
        ('category', String),
        ('news_type', String),
        ('rp_source_id', String),
        ('source_name', String),
        ('provider_id', String),
        ('provider_story_id', String),
        ('headline', String),
        ('css', Float64),
        ('permno', Int64)])

(28148014, 26)

shape: (5, 26)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────┬────────┐
│ timestamp_ ┆ rp_story_i ┆ rp_entity_ ┆ entity_typ ┆ … ┆ provider_s ┆ headline   ┆ css   ┆ permno │
│ utc        ┆ d          ┆ id         ┆ e          ┆   ┆ tory_id    ┆ ---        ┆ ---   ┆ ---    │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str        ┆ f64   ┆ i64    │
│ datetime[n ┆ str        ┆ str        ┆ str        ┆   ┆ str        ┆            ┆       ┆        │
│ s]         ┆            ┆            ┆            ┆   ┆            ┆            ┆       ┆        │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════╪════════╡
│ 2000-01-03 ┆ 70E521E7EA ┆ 479A8C     ┆ COMP       ┆ … ┆ DN20000103 ┆ Sapient    ┆ 0.0   ┆ 83413  │
│ 18:16:00   ┆ 6C5F3A657D ┆            ┆            ┆   ┆ 001404     ┆ Corp       ┆       ┆        │
│            ┆ 5D6B9007F1 ┆            ┆            ┆   ┆            ┆ (SAPE)     ┆       ┆        │
│            ┆ …          ┆            ┆            ┆   ┆            ┆ Block      ┆       ┆        │
│            ┆            ┆            ┆            ┆   ┆            ┆ Equa…      ┆       ┆        │
│ 2000-01-03 ┆ 27D7B949FA ┆ 479A8C     ┆ COMP       ┆ … ┆ DN20000103 ┆ Sapient    ┆ 0.04  ┆ 83413  │
│ 19:30:51   ┆ EC4DE08330 ┆            ┆            ┆   ┆ 001682     ┆ Names      ┆       ┆        │
│            ┆ 688C2DDCAF ┆            ┆            ┆   ┆            ┆ Edward     ┆       ┆        │
│            ┆ …          ┆            ┆            ┆   ┆            ┆ Goldfinge… ┆       ┆        │
│ 2000-01-03 ┆ C4FA1A0C49 ┆ 479A8C     ┆ COMP       ┆ … ┆ DN20000103 ┆ Sapient    ┆ 0.0   ┆ 83413  │
│ 19:48:06   ┆ C581A26D80 ┆            ┆            ┆   ┆ 001730     ┆ Fincl      ┆       ┆        │
│            ┆ 7A9FBCB745 ┆            ┆            ┆   ┆            ┆ Chief -2:  ┆       ┆        │
│            ┆ …          ┆            ┆            ┆   ┆            ┆ Goldfi…    ┆       ┆        │
│ 2000-01-03 ┆ D8C0AE42BD ┆ 47B4CC     ┆ COMP       ┆ … ┆ DN20000103 ┆ Loral      ┆ -0.06 ┆ 22348  │
│ 15:26:00   ┆ DC44AF56EF ┆            ┆            ┆   ┆ 000610     ┆ Space      ┆       ┆        │
│            ┆ 2252AA8202 ┆            ┆            ┆   ┆            ┆ (LOR)      ┆       ┆        │
│            ┆ …          ┆            ┆            ┆   ┆            ┆ Block      ┆       ┆        │
│            ┆            ┆            ┆            ┆   ┆            ┆ Equals…    ┆       ┆        │
│ 2000-01-03 ┆ E10D031FC0 ┆ 47B4CC     ┆ COMP       ┆ … ┆ DN20000103 ┆ Loral      ┆ 0.0   ┆ 22348  │
│ 15:55:37   ┆ 0A463E5C64 ┆            ┆            ┆   ┆ 000752     ┆ Space      ┆       ┆        │
│            ┆ 50F2E4B9FE ┆            ┆            ┆   ┆            ┆ (LOR) Ind: ┆       ┆        │
│            ┆ …          ┆            ┆            ┆   ┆            ┆ 26-28. …   ┆       ┆        │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────┴────────┘

### task_clean_data

In [25]:
parquet_files = [
    "ravenpack_clean.parquet",
]

for pf in parquet_files:
    print(pf)
    df = pl.scan_parquet(DATA_DIR / pf)
    display(df.collect_schema())
    print(df.collect().shape)
    display(df.head().collect())

with open(DATA_DIR / "ravenpack_stage_counts.json", "r") as f:
    ravenpack_stage_counts = json.load(f)

# Display the contents
display(ravenpack_stage_counts)

ravenpack_clean.parquet

Schema([('timestamp_utc', Datetime(time_unit='ns', time_zone=None)),
        ('rp_story_id', String),
        ('rp_entity_id', String),
        ('entity_type', String),
        ('entity_name', String),
        ('country_code', String),
        ('relevance', Float64),
        ('event_sentiment_score', Float64),
        ('event_relevance', Float64),
        ('event_similarity_key', String),
        ('event_similarity_days', Float64),
        ('topic', String),
        ('rp_group', String),
        ('rp_type', String),
        ('sub_type', String),
        ('property', String),
        ('fact_level', String),
        ('category', String),
        ('news_type', String),
        ('rp_source_id', String),
        ('source_name', String),
        ('provider_id', String),
        ('provider_story_id', String),
        ('headline', String),
        ('css', Float64),
        ('permno', Float64),
        ('article_date', Date)])

(14561764, 27)

shape: (5, 27)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬──────┬─────────┬────────────┐
│ timestamp_ ┆ rp_story_i ┆ rp_entity_ ┆ entity_typ ┆ … ┆ headline   ┆ css  ┆ permno  ┆ article_da │
│ utc        ┆ d          ┆ id         ┆ e          ┆   ┆ ---        ┆ ---  ┆ ---     ┆ te         │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ str        ┆ f64  ┆ f64     ┆ ---        │
│ datetime[n ┆ str        ┆ str        ┆ str        ┆   ┆            ┆      ┆         ┆ date       │
│ s]         ┆            ┆            ┆            ┆   ┆            ┆      ┆         ┆            │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪══════╪═════════╪════════════╡
│ 2009-10-20 ┆ A485EF56E0 ┆ 39692D     ┆ COMP       ┆ … ┆ Expedia    ┆ 0.02 ┆ 90808.0 ┆ 2009-10-21 │
│ 13:17:35.2 ┆ CB4A751981 ┆            ┆            ┆   ┆ Started At ┆      ┆         ┆            │
│ 35         ┆ A4E53A06B1 ┆            ┆            ┆   ┆ Outperform ┆      ┆         ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ …          ┆      ┆         ┆            │
│ 2018-04-17 ┆ 5799013CA9 ┆ 054E7E     ┆ COMP       ┆ … ┆ Arcus Bios ┆ 0.02 ┆ 17374.0 ┆ 2018-04-18 │
│ 13:00:01.6 ┆ 6A31604E8E ┆            ┆            ┆   ┆ ciences    ┆      ┆         ┆            │
│ 69         ┆ 02817CC56C ┆            ┆            ┆   ┆ Presents   ┆      ┆         ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ Pha…       ┆      ┆         ┆            │
│ 2006-06-22 ┆ E3D1D11082 ┆ C35C7D     ┆ COMP       ┆ … ┆ Goodrich   ┆ 0.06 ┆ 12140.0 ┆ 2006-06-22 │
│ 20:28:10.0 ┆ 4CDCB655AF ┆            ┆            ┆   ┆ Announces  ┆      ┆         ┆            │
│ 46         ┆ D2A8D6C6A4 ┆            ┆            ┆   ┆ Successful ┆      ┆         ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ …          ┆      ┆         ┆            │
│ 2018-04-24 ┆ A15F85387A ┆ CFF97C     ┆ COMP       ┆ … ┆ S&PGR      ┆ 0.0  ┆ 17478.0 ┆ 2018-04-24 │
│ 19:25:39.7 ┆ 1B7D21B146 ┆            ┆            ┆   ┆ Affirms    ┆      ┆         ┆            │
│ 36         ┆ CF70131455 ┆            ┆            ┆   ┆ 'BBB+/A-2' ┆      ┆         ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ Ratin…     ┆      ┆         ┆            │
│ 2012-01-11 ┆ DA40F4C7F3 ┆ D57D99     ┆ COMP       ┆ … ┆ CHART      ┆ 0.0  ┆ 27430.0 ┆ 2012-01-11 │
│ 19:16:05.1 ┆ 174A3BF0C8 ┆            ┆            ┆   ┆ Cooper     ┆      ┆         ┆            │
│ 74         ┆ 5FDECB0EB0 ┆            ┆            ┆   ┆ Tire &     ┆      ┆         ┆            │
│            ┆ …          ┆            ┆            ┆   ┆ Rubber     ┆      ┆         ┆            │
│            ┆            ┆            ┆            ┆   ┆ ST:…       ┆      ┆         ┆            │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴──────┴─────────┴────────────┘

{'0_raw': 28148014,
 '1_single_entity': 28148014,
 '2_has_return': 23850926,
 '3_length_filter': 23850922,
 '4_deduplicated': 14561764}

### task_labels

In [26]:
parquet_files = [
    "labeled_dataset.parquet",
]

for pf in parquet_files:
    print(pf)
    df = pl.scan_parquet(DATA_DIR / pf)
    display(df.collect_schema())
    print(df.collect().shape)
    display(df.head().collect())

labeled_dataset.parquet

Schema([('rp_story_id', String),
        ('permno', Float64),
        ('article_date', Date),
        ('headline', String),
        ('ret_window', Float64),
        ('market_cap', Float64),
        ('label', Int8)])

(14543821, 7)

shape: (5, 7)
┌───────────────────┬─────────┬──────────────┬───────────────────┬────────────┬────────────┬───────┐
│ rp_story_id       ┆ permno  ┆ article_date ┆ headline          ┆ ret_window ┆ market_cap ┆ label │
│ ---               ┆ ---     ┆ ---          ┆ ---               ┆ ---        ┆ ---        ┆ ---   │
│ str               ┆ f64     ┆ date         ┆ str               ┆ f64        ┆ f64        ┆ i8    │
╞═══════════════════╪═════════╪══════════════╪═══════════════════╪════════════╪════════════╪═══════╡
│ 1A2E1E8678366A1DC ┆ 17478.0 ┆ 1999-12-31   ┆ Standard & Poor's ┆ -0.018887  ┆ 1.2085e10  ┆ 0     │
│ 76567515458F4…    ┆         ┆              ┆ Closing Stoc…     ┆            ┆            ┆       │
│ 2E0605C87A496B9AB ┆ 10104.0 ┆ 2000-01-03   ┆ Oracle (ORCL)     ┆ -0.033109  ┆ 1.6817e11  ┆ 0     │
│ E5A435E72EC40…    ┆         ┆              ┆ Block: 100,000 S… ┆            ┆            ┆       │
│ 20AC96B446A991E93 ┆ 10104.0 ┆ 2000-01-03   ┆ Oracle (ORCL)     ┆ -0.033109  ┆ 1.6817e11  ┆ 0     │
│ 872D3479FF746…    ┆         ┆              ┆ Block: 100,000 S… ┆            ┆            ┆       │
│ C6ED0131AF86D935F ┆ 10104.0 ┆ 2000-01-03   ┆ Oracle (ORCL)     ┆ -0.033109  ┆ 1.6817e11  ┆ 0     │
│ 1B1B53D82A028…    ┆         ┆              ┆ Block: 100,000 S… ┆            ┆            ┆       │
│ B2EC50CD81FCF233F ┆ 10104.0 ┆ 2000-01-03   ┆ Oracle (ORCL)     ┆ -0.033109  ┆ 1.6817e11  ┆ 0     │
│ 50726F7CCC108…    ┆         ┆              ┆ Block: 100,000 S… ┆            ┆            ┆       │
└───────────────────┴─────────┴──────────────┴───────────────────┴────────────┴────────────┴───────┘

In [28]:
df = pd.read_parquet(DATA_DIR / "labeled_dataset.parquet")
df

,rp_story_id,permno,article_date,headline,ret_window,market_cap,label
0,1A2E1E8678366A1DC76567515458F442,17478.0,1999-12-31,Standard & Poor's Closing Stock Indexes,-0.018887,1.208466e+10,0
1,2E0605C87A496B9ABE5A435E72EC402D,10104.0,2000-01-03,"Oracle (ORCL) Block: 100,000 Shares At 116 1/16",-0.033109,1.681713e+11,0
2,20AC96B446A991E93872D3479FF7466C,10104.0,2000-01-03,"Oracle (ORCL) Block: 100,000 Shrs At 124 1/2",-0.033109,1.681713e+11,0
3,C6ED0131AF86D935F1B1B53D82A028A0,10104.0,2000-01-03,"Oracle (ORCL) Block: 100,000 Shares At 123 13/32",-0.033109,1.681713e+11,0
4,B2EC50CD81FCF233F50726F7CCC108AD,10104.0,2000-01-03,"Oracle (ORCL) Block: 100,000 Shares At 115 11/16",-0.033109,1.681713e+11,0
...,...,...,...,...,...,...,...
14543816,65DF8D9421F838BC1DFE6A52ADE4E35F,88446.0,2019-07-01,Illumina: Patent Complaint Filed Against Latvi...,0.041711,5.448849e+10,1
14543817,18129221DA015F2243824517A55D2789,88446.0,2019-07-01,Illumina Files Patent Infringement Suits Relat...,0.041711,5.448849e+10,1
14543818,1E94990F3893EA20150B176126E7C369,88446.0,2019-07-01,Illumina: Patent Complaint Filed Against Compl...,0.041711,5.448849e+10,1
14543819,F2B69DFB028065DD63EE5F3071365624,89626.0,2019-07-01,CME Group Agricultural Estimated Volumes At 9:...,0.030273,7.021074e+10,1
14543820,1AA2D3ED0C97F5FBF2982DDC3099D2ED,91754.0,2019-07-01,ISG Research Identifies Top Growth Industries ...,-0.030488,1.487430e+08,0

### task_merge_sector

In [29]:
parquet_files = [
    "labeled_dataset_with_sector.parquet",
]

for pf in parquet_files:
    print(pf)
    df = pl.scan_parquet(DATA_DIR / pf)
    display(df.collect_schema())
    print(df.collect().shape)
    display(df.head().collect())

labeled_dataset_with_sector.parquet

Schema([('rp_story_id', String),
        ('permno', Float64),
        ('article_date', Date),
        ('headline', String),
        ('ret_window', Float64),
        ('market_cap', Float64),
        ('label', Int8),
        ('gsector', String),
        ('sector_name', String)])

(5810325, 9)

shape: (5, 9)
┌─────────────┬─────────┬─────────────┬────────────┬───┬────────────┬───────┬─────────┬────────────┐
│ rp_story_id ┆ permno  ┆ article_dat ┆ headline   ┆ … ┆ market_cap ┆ label ┆ gsector ┆ sector_nam │
│ ---         ┆ ---     ┆ e           ┆ ---        ┆   ┆ ---        ┆ ---   ┆ ---     ┆ e          │
│ str         ┆ f64     ┆ ---         ┆ str        ┆   ┆ f64        ┆ i8    ┆ str     ┆ ---        │
│             ┆         ┆ date        ┆            ┆   ┆            ┆       ┆         ┆ str        │
╞═════════════╪═════════╪═════════════╪════════════╪═══╪════════════╪═══════╪═════════╪════════════╡
│ 1A2E1E86783 ┆ 17478.0 ┆ 1999-12-31  ┆ Standard & ┆ … ┆ 1.2085e10  ┆ 0     ┆ 25      ┆ Consumer   │
│ 66A1DC76567 ┆         ┆             ┆ Poor's     ┆   ┆            ┆       ┆         ┆ Discretion │
│ 515458F4…   ┆         ┆             ┆ Closing    ┆   ┆            ┆       ┆         ┆ ary        │
│             ┆         ┆             ┆ Stoc…      ┆   ┆            ┆       ┆         ┆            │
│ 2E0605C87A4 ┆ 10104.0 ┆ 2000-01-03  ┆ Oracle     ┆ … ┆ 1.6817e11  ┆ 0     ┆ 45      ┆ Informatio │
│ 96B9ABE5A43 ┆         ┆             ┆ (ORCL)     ┆   ┆            ┆       ┆         ┆ n          │
│ 5E72EC40…   ┆         ┆             ┆ Block:     ┆   ┆            ┆       ┆         ┆ Technology │
│             ┆         ┆             ┆ 100,000 S… ┆   ┆            ┆       ┆         ┆            │
│ 20AC96B446A ┆ 10104.0 ┆ 2000-01-03  ┆ Oracle     ┆ … ┆ 1.6817e11  ┆ 0     ┆ 45      ┆ Informatio │
│ 991E93872D3 ┆         ┆             ┆ (ORCL)     ┆   ┆            ┆       ┆         ┆ n          │
│ 479FF746…   ┆         ┆             ┆ Block:     ┆   ┆            ┆       ┆         ┆ Technology │
│             ┆         ┆             ┆ 100,000 S… ┆   ┆            ┆       ┆         ┆            │
│ C6ED0131AF8 ┆ 10104.0 ┆ 2000-01-03  ┆ Oracle     ┆ … ┆ 1.6817e11  ┆ 0     ┆ 45      ┆ Informatio │
│ 6D935F1B1B5 ┆         ┆             ┆ (ORCL)     ┆   ┆            ┆       ┆         ┆ n          │
│ 3D82A028…   ┆         ┆             ┆ Block:     ┆   ┆            ┆       ┆         ┆ Technology │
│             ┆         ┆             ┆ 100,000 S… ┆   ┆            ┆       ┆         ┆            │
│ B2EC50CD81F ┆ 10104.0 ┆ 2000-01-03  ┆ Oracle     ┆ … ┆ 1.6817e11  ┆ 0     ┆ 45      ┆ Informatio │
│ CF233F50726 ┆         ┆             ┆ (ORCL)     ┆   ┆            ┆       ┆         ┆ n          │
│ F7CCC108…   ┆         ┆             ┆ Block:     ┆   ┆            ┆       ┆         ┆ Technology │
│             ┆         ┆             ┆ 100,000 S… ┆   ┆            ┆       ┆         ┆            │
└─────────────┴─────────┴─────────────┴────────────┴───┴────────────┴───────┴─────────┴────────────┘

### task_text_stats

In [30]:
# Read "text_stats.json"
with open("text_stats.json", "r") as f:
    text_stats = json.load(f)

# Display the contents
display(text_stats)

FileNotFoundError: [Errno 2] No such file or directory: 'text_stats.json'

### task_embed

In [43]:
bert_df = pd.read_parquet(DATA_DIR / "embeddings_bert_chunks" / "chunk_000000.parquet")
display(bert_df)

,rp_story_id,dim_0,dim_1,dim_2,dim_3,dim_4,dim_5,dim_6,dim_7,dim_8,...,dim_758,dim_759,dim_760,dim_761,dim_762,dim_763,dim_764,dim_765,dim_766,dim_767
0,8CEFBDEE531A5B7FE6F333DB53030250,-0.116917,-0.182524,0.506346,0.363480,0.209670,0.035555,-0.223356,0.281024,0.153399,...,-0.156539,0.022419,0.084681,-0.357854,0.184221,0.030479,0.067035,-0.171768,0.149112,0.197864
1,990D3B3EC1464BD7F46C9139871804CB,-0.055783,0.105771,0.251373,-0.108172,0.385930,-0.127051,-0.023832,0.332632,-0.044101,...,0.076275,0.036145,0.056646,-0.296372,0.298303,-0.064585,-0.043022,-0.028945,-0.167014,0.079209
2,75B6B240DC1456981F0B81BE00B9D13F,-0.297897,-0.195372,0.335441,0.003808,0.391972,-0.265315,-0.220866,0.186222,0.136440,...,-0.086622,0.092377,-0.021653,-0.338054,-0.080933,-0.079960,-0.193212,-0.226865,0.120592,0.084130
3,9BB81CA68D6FA2C7D8893CEE41366F01,-0.128196,-0.115851,0.391839,0.050869,0.185566,-0.206569,0.016583,0.182701,0.197443,...,0.221644,0.101192,-0.127763,-0.091701,0.258072,0.055339,-0.359308,-0.080543,0.076060,0.017643
4,848030C4946B1DFC9276BD4D20F26215,-0.037816,-0.176356,0.063950,0.258025,0.175954,-0.397377,0.247195,0.153450,0.021403,...,-0.027567,0.176034,0.206885,-0.323045,0.247065,0.095669,-0.204133,-0.047537,0.185398,0.277455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4219,402D3C99624B643089A07BD630D06B44,0.001976,-0.045169,0.678524,-0.076896,0.112215,-0.069368,0.132644,-0.020124,-0.131993,...,0.104929,0.236857,0.015021,-0.298427,0.418981,0.084499,-0.074037,0.030221,0.097586,0.054718
4220,B1632C178146A8B7ACDCF065825ACBE3,-0.211947,-0.420222,0.401340,0.060698,0.592271,-0.623041,-0.060276,0.588759,0.176029,...,-0.105087,0.052221,0.047846,-0.252017,0.086564,0.263346,0.302141,-0.248383,-0.055336,-0.324494
4221,CAA624750EE41890B12291B6C100AF91,-0.264368,-0.340366,0.005634,-0.267077,0.067193,0.125652,0.081688,0.576540,0.006071,...,0.069055,0.155007,0.117297,-0.446672,0.342875,-0.138178,0.236791,-0.125392,0.071143,0.067288
4222,33B214E1C7C9FB4D71D624E686BFB7D0,0.226331,-0.218150,0.369960,0.056981,0.127110,-0.445958,-0.022770,0.463435,-0.074499,...,0.256184,-0.106097,-0.143139,-0.382032,0.300852,-0.449859,-0.366420,-0.253726,-0.011195,0.283934
4223,4D45E864C63763FF7C10C76EB3BA87DB,0.077034,-0.330416,0.211865,0.066503,-0.094589,-0.064263,0.076691,-0.020958,0.335161,...,0.038333,0.098914,-0.181616,-0.416635,0.278455,0.026826,-0.027960,-0.066820,0.205509,0.098908

In [44]:
gemma_df = pd.read_parquet(DATA_DIR / "embeddings_gemma_chunks" / "chunk_000000.parquet")
display(gemma_df)

,rp_story_id,dim_0,dim_1,dim_2,dim_3,dim_4,dim_5,dim_6,dim_7,dim_8,...,dim_758,dim_759,dim_760,dim_761,dim_762,dim_763,dim_764,dim_765,dim_766,dim_767
0,F11683ABF7D66C0E900A7A741573B37D,-0.183686,0.054091,-0.021224,-0.018533,-0.008218,0.044978,-0.040575,0.025868,-0.027862,...,-0.019117,-0.000395,-0.037498,-0.013307,0.010110,0.051601,0.007747,0.077298,-0.017298,-0.019159
1,BA835B80DE149221EE8F491CD1933723,-0.114195,-0.021118,0.014177,0.014552,0.035219,0.004481,-0.022207,0.060181,-0.001322,...,-0.033251,-0.024747,-0.061583,0.000154,0.007563,-0.034012,-0.004031,0.052421,0.008162,-0.044229
2,FEF146612237A565204E67499BB8E8DA,-0.123113,-0.012299,-0.036610,0.057795,0.008670,0.011611,-0.027515,0.039888,-0.019306,...,-0.019350,0.003127,-0.062027,-0.000221,-0.001506,0.004150,-0.012450,0.003175,-0.023925,-0.021916
3,16DED71384F04913842E3F803AB0EE50,-0.177629,-0.059869,0.001468,-0.012262,-0.040162,0.066116,0.005849,0.051366,-0.006996,...,-0.073013,0.045546,-0.022252,0.072441,0.001929,0.007484,-0.014653,-0.010331,-0.036332,-0.057454
4,1643FD42EC2F240FDEFDAD61C2B7C986,-0.138809,-0.017202,-0.050121,0.031292,-0.031284,0.027316,-0.025373,0.014630,0.001707,...,-0.044969,0.018368,-0.029910,0.003602,0.012250,0.001906,-0.026818,0.012590,-0.050965,-0.002381
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,6A079ACACB40950D3C1477A1680B2376,-0.132978,-0.018246,-0.012835,0.011667,-0.021946,0.039228,-0.037099,0.060495,0.001461,...,-0.040982,-0.015707,-0.015743,0.027974,0.002743,0.011777,-0.058779,0.044292,-0.034125,-0.041500
6396,9C9D4CF53F1A7F29DE4E2E12C12537B8,-0.155096,-0.009551,-0.023517,0.008083,-0.025621,0.025367,-0.016595,0.093486,0.005016,...,-0.067759,-0.011981,-0.054728,0.031611,-0.011296,-0.016727,-0.031393,-0.036917,-0.015529,-0.023750
6397,EF8FEA3085BB980CAA18D6FB95278E27,-0.126291,0.033008,0.002193,0.036335,0.042963,0.002361,-0.001898,0.070182,0.001977,...,-0.005315,-0.022890,-0.049289,0.021163,0.009138,-0.006013,-0.006626,0.064730,-0.004053,-0.020106
6398,497DFDE230458F54BAE47E6EC5B99DF2,-0.166118,0.013447,-0.006958,-0.023023,0.011162,0.028816,-0.005948,0.078584,-0.027558,...,-0.009365,-0.043183,-0.070234,-0.020045,-0.003566,-0.031512,-0.024238,-0.023377,0.001455,-0.049868
6399,7A81F4CD9C477AA4E1F4CE9400254455,-0.116102,0.028207,0.028031,0.023147,-0.019296,0.037010,-0.011464,0.045460,0.000870,...,-0.030803,-0.029084,-0.067234,-0.012780,0.016315,0.010071,-0.016901,0.028878,0.013631,0.002263

In [45]:
# find a common `rp_story_id` between the two datasets
common_rp_story_id = set(bert_df['rp_story_id']).intersection(set(gemma_df['rp_story_id']))
common_rp_story_id

{'7B82075FB185D295FAB83D2467CDCB64', 'C79D1CCA9FB99B9B8190DD961C452F00'}

In [67]:
common = pd.concat([bert_df[bert_df['rp_story_id'] == "7B82075FB185D295FAB83D2467CDCB64"],
                    gemma_df[gemma_df['rp_story_id'] == "7B82075FB185D295FAB83D2467CDCB64"]])
common.reset_index(drop=True, inplace=True)

common.loc[0, "rp_story_id"] = "BERT_" + "7B82075FB185D295FAB83D2467CDCB64"
common.loc[1, "rp_story_id"] = "GEMMA_" + "7B82075FB185D295FAB83D2467CDCB64"

common.set_index("rp_story_id", inplace=True)
common

,dim_0,dim_1,dim_2,dim_3,dim_4,dim_5,dim_6,dim_7,dim_8,dim_9,...,dim_758,dim_759,dim_760,dim_761,dim_762,dim_763,dim_764,dim_765,dim_766,dim_767
rp_story_id,,,,,,,,,,,,,,,,,,,,,
BERT_7B82075FB185D295FAB83D2467CDCB64,-0.161089,0.094028,0.386005,0.169368,0.602279,-0.184194,0.109360,0.323831,0.148411,-0.401488,...,0.110722,-0.025234,0.154365,-0.117831,0.502217,-0.058414,-0.109000,-0.236253,-0.038249,0.049186
GEMMA_7B82075FB185D295FAB83D2467CDCB64,-0.148629,0.038470,-0.020406,0.005287,0.002351,0.052261,0.002413,0.056078,0.036504,0.000218,...,0.016532,0.025593,-0.027852,-0.000976,-0.002668,0.006046,-0.018069,0.042065,0.011715,-0.043610